### PR TITLE
Document getCurrentProcessMaps (#36); improve pyQBDI documentation

### PR DESCRIPTION
**Pull request by nezetic**
Should solve the issue #36.
I didn't documented getRemoteProcessMaps as it's not really a public API...

Documentation has been improved, but :

- CPP API doc rendering is broken with the latest version of Sphinx and breathe
- pyQBDI documentation could really still be improved

### CODE REVIEW

**Comment by nezetic** [comment]
Also worth noting that memory map and related APIs are not exposed in C bindings (and thus in Frida).

But for Frida they are not useful as Frida already provides everything.

**Comment by haxelion** [comment]
Ok this is pretty good for me and renders correctly on my "old" version of sphinx (1.6.3).
We can investigate newer version rendering problems later.

**Comment by nezetic** [comment]
I switched back my sphinx installation to the 1.6 branch (1.6.7) and indeed, I don't have any issue. We will investigate what changed in the 1.7 branch later.

**Comment by nezetic** [comment]
I've fixed known working versions of sphinx and breathe in the doc requirements.txt (86a702db2b2946a8d9dce54b6a997ccd89895caf)

**Pull request merged**
